# Generated by Django 4.0.2 on 2022-03-05 19:29

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticketgeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketid', models.CharField(max_length=36, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name=django.contrib.auth.models.User)),
                ('email', models.EmailField(max_length=254)),
                ('checkbox', models.CharField(max_length=256)),
                ('adult', models.CharField(max_length=100)),
                ('fromstation', models.CharField(max_length=256)),
                ('tostation', models.CharField(max_length=256)),
                ('rate', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('usermessage', models.CharField(max_length=500)),
            ],
        ),
    ]
