# Generated by Django 4.0.2 on 2022-04-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketgeneration',
            old_name='user',
            new_name='username',
        ),
    ]
